services:
  api:
    build: .
    image: dm-api:ci
    environment:
      - PORT=5000
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=last_metro_db
      - POSTGRES_PORT=5432
    ports:
      - "5000:5000"
    depends_on:
      - last_metro_db
    networks:
      - "last_metro_network"

  swagger:
    image: swaggerapi/swagger-ui:latest
    environment:
      - SWAGGER_JSON=/usr/share/nginx/html/openapi/openapi.yml
    volumes:
      - ./openapi:/usr/share/nginx/html/openapi:ro
    ports:
      - "8080:8080"
    depends_on:
      - api
    networks:
      - "last_metro_network"

  last_metro_db:
    container_name: "last_metro_db"
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_TEST_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_TEST_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_TEST_DB}"
    env_file:
      - .env
    networks:
      - "last_metro_network"

  last_metro_db_test:
    container_name: "last_metro_db_test"
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_test_data:/var/lib/postgresql/data/
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_TEST_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_TEST_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_TEST_DB}"
    env_file:
      - .env
    networks:
      - "last_metro_network"

volumes:
  postgres_data:
  postgres_test_data:

networks:
  last_metro_network:
    driver: bridge
